{{- if .Values.secrets }}
{{- range $secret := .Values.secrets }}
---
apiVersion: v1
stringData:
  {{- range $key, $value := $secret.values }}
  {{ $key }}: {{ $value }}  
  {{- end }}
kind: Secret
metadata:
  name: {{ $secret.name }}
  namespace: {{ $secret.namespace }}  
type: {{ $secret.type }}
{{- end }}
{{- end }}
