name: 'Test'

# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the develop branch
  push:
    branches: [ develop ]

env:
  NODE_VERSION: '16.x'

jobs:
  int-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Build Application
        run: npm ci

      - name: Run e2e tests
      - run: npm run test:e2e

  # unit-tests:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Setup Node.js
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: ${{ env.NODE_VERSION }}

  #     - name: Build Application
  #       run: npm ci

  #     - name: Run e2e tests
  #     - run: npm run test:e2e