name: 'Test'

on:
  pull_request:

env:
  NODE_VERSION: '16.x'

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
            fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Build Application
        run: npm ci

      - name: Run e2e tests
        run: npm run test:e2e

      - name: Publish report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: E2ETestReport
          path: ./e2e-test-report.html

  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
            fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Build Application
        run: npm ci

      - name: Run unit tests
        run: npm run test:unit

      - name: Publish report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: UnitTestReport
          path: ./unit-test-report.html