lint:
    stage: lint
    image: ${CI_DEPENDENCY_PROXY_DIRECT_GROUP_IMAGE_PREFIX}/node:14
    before_script:
        - npm ci
    script:
        - ls -l
        - npx eslint './src/**/*.ts' -f json -o ./eslint.json || exit 0
    artifacts:
        paths:
            - eslint.json
    only:
        - merge_requests
